-- 코드를 작성해주세요
SELECT a.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO as a INNER JOIN ITEM_TREE as b ON a.ITEM_ID = b.ITEM_ID
WHERE a.ITEM_ID IN
(
SELECT d.ITEM_ID
FROM ITEM_INFO as c INNER JOIN ITEM_TREE as d ON c.ITEM_ID = d.PARENT_ITEM_ID
WHERE RARITY = 'RARE'
AND PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID desc;